---
name: Release Checklist
description: Create a release issue
title: "[RELEASE]"
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: The version that is being released.
      placeholder: ex. 0.4.1-rc.1
    validations:
      required: true
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: The tasks required to consider this release complete. (Please complete the assignee in the task description).
      options:
        - label: confirm works reasonably in the field someplace
