name: HcBuild
on:
  workflow_dispatch:
jobs:
  hc-build:
    runs-on: ubuntu-latest
    container:
      image: dockbuild/ubuntu1804-gcc7:latest
    steps:
      - name: Print Glibc Version
        run: ldd --version ldd

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '=1.20.0'

      - name: Build holochain
        run: PATH=~/.cargo/bin:$PATH cargo install holochain@0.5.0-dev.1

      - name: Print holochain ldd
        run: ldd ~/.cargo/bin/holochain
