name: HcBuild
on:
  workflow_dispatch:
jobs:
  hc-build:
    runs-on: ubuntu-latest
    container:
      image: dockbuild/ubuntu1804-gcc7:latest
    steps:
      - name: Print Glibc Version
        run: ldd --version ldd

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y

      - name: Install Go
        run: |
          curl -LO curl -O https://go.dev/dl/go1.20.14.linux-amd64.tar.gz
          tar xf go1.20.14.linux-amd64.tar.gz
          echo ~/go/bin
          ls ~/go/bin/
          PATH=~/go/bin:$PATH go version

          #- name: Build holochain
        #run: PATH=~/.cargo/bin:~/go/bin:$PATH cargo install holochain@0.5.0-dev.1

          #- name: Print holochain ldd
        #run: ldd ~/.cargo/bin/holochain
